import type { Metadata } from "next";
import { SiteChrome } from "@/components/layout/site-chrome";
import "./globals.css";

const siteUrl = "https://arena.xflux.cn"

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "Design Skill Arena",
    template: "%s | Design Skill Arena",
  },
  description:
    "Design Skill Arena 是一个中英文静态展示站，用同一个 Muse AI Campaign Studio 需求展示不同 AI 模型与前端设计 skill chain 生成的真实页面效果。",
  alternates: {
    canonical: "/",
    languages: {
      "zh-CN": "/",
      "en-US": "/",
    },
  },
  openGraph: {
    type: "website",
    url: siteUrl,
    siteName: "Design Skill Arena",
    title: "Design Skill Arena",
    description:
      "Browse standalone Muse AI Campaign Studio pages generated by different AI models and frontend design skill chains.",
    locale: "zh_CN",
    alternateLocale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Design Skill Arena",
    description:
      "A bilingual static gallery of AI frontend design skill outputs for Muse AI Campaign Studio.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className="h-full antialiased">
      <body className="flex min-h-full flex-col">
        <SiteChrome>{children}</SiteChrome>
      </body>
    </html>
  );
}
